project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'backend', 'interface', 'OSA'));

result = wavelength_sweep( ...
    'lam_start_nm', 1549.5, ...
    'lam_stop_nm', 1550.5, ...
    'resolution_nm', 0.1, ...
    'points_per_resolution', 5, ...
    'speed', '2x', ...
    'board_index', 0, ...
    'primary_address', 1, ...
    'timeout_s', 30, ...
    'plot_result', false, ...
    'record', false ...
);

fprintf('OSA_POINTS=%d\n', numel(result.wavelength_nm));
fprintf('OSA_START_NM=%.6f\n', result.wavelength_nm(1));
fprintf('OSA_STOP_NM=%.6f\n', result.wavelength_nm(end));
fprintf('OSA_MAX_DBM=%.6f\n', max(result.power_dbm));
fprintf('OSA_MIN_DBM=%.6f\n', min(result.power_dbm));
